x-base_service: &base_service
  stdin_open: true # docker run -i
  tty: true # docker run -t
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


services:
  download-webui:
    build: ./webui/services/download/
    profiles: ["download"]
    volumes:
      - ./webui/data:/data

  auto:
    <<: *base_service
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - ./webui/data:/data
      - ./webui/output:/output
    stop_signal: SIGKILL
    profiles: ["auto"]
    build: ./webui/services/AUTOMATIC1111
    image: sd-auto:78
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api


  orchestration:
    <<: *base_service
    build: ./orchestration
    profiles: ["orchestration"]
    develop:
      watch:
        - action: sync
          path: ./orchestration/
          target: /code/orchestration/
    ports:
      - "8000:80"

  fit_garment:
    <<: *base_service
    build: ./fit_garment
    profiles: ["fit_garment"]
    develop:
      watch:
        - action: sync
          path: ./fit_garment/
          target: /code/fit_garment/
        - action: sync
          path: ./fit_garment_integration_tests/
          target: /code/fit_garment_integration_tests/
        - action: rebuild
          path: ./fit_garment/Dockerfile

  create_pose:
    <<: *base_service
    build: ./create_pose
    profiles: ["create_pose"]
    develop:
      watch:
        - action: sync
          path: ./create_pose/scripts
          target: /home/myuser/SMPLitex/scripts
        - action: sync
          path: ./create_pose/sample-data
          target: /home/myuser/SMPLitex/sample-data
